[package]
name = "dotsimp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
regex = "1.7.0"
serde = { version = "1.0.151", features = ["derive"] }
symlink = "0.1.0"
toml = "0.5.10"
